ALTER TABLE revenues ADD COLUMN IF NOT EXISTS "Income" NUMERIC(12,2) DEFAULT 0;
ALTER TABLE revenues ADD COLUMN IF NOT EXISTS "Expenses" NUMERIC(12,2) DEFAULT 0;
ALTER TABLE revenues ADD COLUMN IF NOT EXISTS income NUMERIC(12,2) DEFAULT 0;
ALTER TABLE revenues ADD COLUMN IF NOT EXISTS expenses NUMERIC(12,2) DEFAULT 0;
